trigger:
- main

pool:
  my_agent_pool

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'C:\Users\Iskandar_Khudzhamkul\agent'
    Contents: '**.pbix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'